<?php

use Illuminate\Database\Seeder;

class TestAddictionTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('test_addiction')->insert([
            [
                'test_id' => 2, 
                'addiction_id' => 1,
                'test_information_id' => 4,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'test_id' => 2, 
                'addiction_id' => 1,
                'test_information_id' => 5,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'test_id' => 2, 
                'addiction_id' => 1,
                'test_information_id' => 6,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'test_id' => 2, 
                'addiction_id' => 2,
                'test_information_id' => 7,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'test_id' => 2, 
                'addiction_id' => 2,
                'test_information_id' => 8,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'test_id' => 2, 
                'addiction_id' => 2,
                'test_information_id' => 9,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'test_id' => 2, 
                'addiction_id' => 3,
                'test_information_id' => 10,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'test_id' => 2, 
                'addiction_id' => 3,
                'test_information_id' => 11,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'test_id' => 2, 
                'addiction_id' => 3,
                'test_information_id' => 12,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'test_id' => 2, 
                'addiction_id' => 4,
                'test_information_id' => 13,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'test_id' => 2, 
                'addiction_id' => 4,
                'test_information_id' => 14,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'test_id' => 2, 
                'addiction_id' => 4,
                'test_information_id' => 15,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'test_id' => 2, 
                'addiction_id' => 5,
                'test_information_id' => 16,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'test_id' => 2, 
                'addiction_id' => 5,
                'test_information_id' => 17,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'test_id' => 2, 
                'addiction_id' => 5,
                'test_information_id' => 18,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'test_id' => 2, 
                'addiction_id' => 6,
                'test_information_id' => 19,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'test_id' => 2, 
                'addiction_id' => 6,
                'test_information_id' => 20,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'test_id' => 2, 
                'addiction_id' => 6,
                'test_information_id' => 21,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'test_id' => 2, 
                'addiction_id' => 7,
                'test_information_id' => 22,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'test_id' => 2, 
                'addiction_id' => 7,
                'test_information_id' => 23,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'test_id' => 2, 
                'addiction_id' => 7,
                'test_information_id' => 24,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'test_id' => 2, 
                'addiction_id' => 27,
                'test_information_id' => 25,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'test_id' => 2, 
                'addiction_id' => 27,
                'test_information_id' => 26,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'test_id' => 2, 
                'addiction_id' => 27,
                'test_information_id' => 27,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'test_id' => 2, 
                'addiction_id' => 28,
                'test_information_id' => 28,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'test_id' => 2, 
                'addiction_id' => 28,
                'test_information_id' => 29,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'test_id' => 2, 
                'addiction_id' => 28,
                'test_information_id' => 30,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'test_id' => 4, 
                'addiction_id' => 18,
                'test_information_id' => 34,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'test_id' => 4, 
                'addiction_id' => 18,
                'test_information_id' => 35,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'test_id' => 4, 
                'addiction_id' => 18,
                'test_information_id' => 36,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'test_id' => 4, 
                'addiction_id' => 19,
                'test_information_id' => 34,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'test_id' => 4, 
                'addiction_id' => 19,
                'test_information_id' => 35,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'test_id' => 4, 
                'addiction_id' => 19,
                'test_information_id' => 36,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'test_id' => 4, 
                'addiction_id' => 20,
                'test_information_id' => 34,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'test_id' => 4, 
                'addiction_id' => 20,
                'test_information_id' => 35,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'test_id' => 4, 
                'addiction_id' => 20,
                'test_information_id' => 36,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'test_id' => 4, 
                'addiction_id' => 21,
                'test_information_id' => 34,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'test_id' => 4, 
                'addiction_id' => 21,
                'test_information_id' => 35,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'test_id' => 4, 
                'addiction_id' => 21,
                'test_information_id' => 36,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'test_id' => 4, 
                'addiction_id' => 22,
                'test_information_id' => 34,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'test_id' => 4, 
                'addiction_id' => 22,
                'test_information_id' => 35,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'test_id' => 4, 
                'addiction_id' => 22,
                'test_information_id' => 36,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'test_id' => 4, 
                'addiction_id' => 23,
                'test_information_id' => 34,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'test_id' => 4, 
                'addiction_id' => 23,
                'test_information_id' => 35,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'test_id' => 4, 
                'addiction_id' => 23,
                'test_information_id' => 36,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'test_id' => 4, 
                'addiction_id' => 24,
                'test_information_id' => 34,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'test_id' => 4, 
                'addiction_id' => 24,
                'test_information_id' => 35,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'test_id' => 4, 
                'addiction_id' => 24,
                'test_information_id' => 36,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'test_id' => 4, 
                'addiction_id' => 25,
                'test_information_id' => 34,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'test_id' => 4, 
                'addiction_id' => 25,
                'test_information_id' => 35,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'test_id' => 4, 
                'addiction_id' => 25,
                'test_information_id' => 36,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'test_id' => 4, 
                'addiction_id' => 26,
                'test_information_id' => 34,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'test_id' => 4, 
                'addiction_id' => 26,
                'test_information_id' => 35,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'test_id' => 4, 
                'addiction_id' => 26,
                'test_information_id' => 36,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'test_id' => 5, 
                'addiction_id' => 10,
                'test_information_id' => 37,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'test_id' => 5, 
                'addiction_id' => 10,
                'test_information_id' => 38,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'test_id' => 5, 
                'addiction_id' => 10,
                'test_information_id' => 39,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'test_id' => 5, 
                'addiction_id' => 11,
                'test_information_id' => 37,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'test_id' => 5, 
                'addiction_id' => 11,
                'test_information_id' => 38,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'test_id' => 5, 
                'addiction_id' => 11,
                'test_information_id' => 39,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'test_id' => 5, 
                'addiction_id' => 12,
                'test_information_id' => 37,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'test_id' => 5, 
                'addiction_id' => 12,
                'test_information_id' => 38,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'test_id' => 5, 
                'addiction_id' => 12,
                'test_information_id' => 39,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'test_id' => 5, 
                'addiction_id' => 14,
                'test_information_id' => 37,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'test_id' => 5, 
                'addiction_id' => 14,
                'test_information_id' => 38,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'test_id' => 5, 
                'addiction_id' => 14,
                'test_information_id' => 39,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'test_id' => 5, 
                'addiction_id' => 15,
                'test_information_id' => 37,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'test_id' => 5, 
                'addiction_id' => 15,
                'test_information_id' => 38,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'test_id' => 5, 
                'addiction_id' => 15,
                'test_information_id' => 39,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'test_id' => 5, 
                'addiction_id' => 16,
                'test_information_id' => 37,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'test_id' => 5, 
                'addiction_id' => 16,
                'test_information_id' => 38,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'test_id' => 5, 
                'addiction_id' => 16,
                'test_information_id' => 39,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'test_id' => 5, 
                'addiction_id' => 17,
                'test_information_id' => 37,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'test_id' => 5, 
                'addiction_id' => 17,
                'test_information_id' => 38,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'test_id' => 5, 
                'addiction_id' => 17,
                'test_information_id' => 39,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
        ]);
    }
}
